# Get the Data 

In [149]:
import pandas as pd 
data = pd.read_csv("../datasets/raw_data.csv")
data.head()  

Unnamed: 0  optionId  bill
0           0    751839     1
1           1    751782     1
2           2    745321     1
3           3    666652     1
4           4    751873     2

In [150]:
data.columns = ['index', 'option', 'bill']

In [151]:
data.head() 

index  option  bill
0      0  751839     1
1      1  751782     1
2      2  745321     1
3      3  666652     1
4      4  751873     2

In [152]:
sample_set = data[:100]

In [153]:
sample_set.shape

(100, 3)

In [154]:
sample_set.bill.unique() 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
      dtype=int64)

In [155]:
# create two list of options 
all_options = sample_set.option.unique()
all_options.shape

(85,)

In [156]:
import numpy as np 

half = int(np.floor(all_options.shape[0] / 2)) 
half 

42

In [157]:
left_options = all_options[:half] 
right_options = all_options[half:]

left_options.shape[0] + right_options.shape[0]

85

In [158]:
right_options[:10], right_options[:10]

(array([705527, 704329, 705522, 705502, 714910, 715013, 753517, 705521,
        677956, 750116], dtype=int64),
 array([705527, 704329, 705522, 705502, 714910, 715013, 753517, 705521,
        677956, 750116], dtype=int64))

In [159]:
import itertools
p = itertools.product(left_options, right_options)

In [160]:
option_pairs = np.array([v for v in p])

In [161]:
option_pairs[:3]

array([[751839, 705527],
       [751839, 704329],
       [751839, 705522]], dtype=int64)

In [162]:
option_rating = dict() 
bills = sample_set.bill.unique() 

bills[:3]

array([1, 2, 3], dtype=int64)

In [163]:
for bill in bills: 
    a = set(sample_set[sample_set.bill == bill]['option'])
    b = set([756488, 752059])
    print(a, b, a & b, bool(a & b))
    break 

{745321, 666652, 751782, 751839} {756488, 752059} set() False


In [164]:
set(option_pairs[0])

{705527, 751839}

In [165]:
%%time 
# traverse for one pair in all bills 
for pair in option_pairs: 
    pair_s = set(pair) 
    for bill in bills: 
        options = set(sample_set[sample_set.bill == bill]['option'])
        if(bool(pair_s & options)):
            option_rating[tuple(pair)] = option_rating.get(tuple(pair), 0) + 1  

In [ ]:
option_rating

{(752013, 749689): 3,
 (752013, 756416): 4,
 (752013, 756431): 2,
 (752013, 756419): 2,
 (752013, 754172): 2,
 (752013, 761234): 2,
 (752013, 757816): 3,
 (752013, 747027): 2,
 (752013, 758223): 2,
 (752013, 757820): 3,
 (752013, 756398): 2,
 (752013, 752093): 2,
 (752013, 752049): 2,
 (752013, 756906): 2,
 (752013, 711127): 2,
 (752013, 756423): 2,
 (752013, 757762): 2,
 (752013, 785918): 2,
 (752013, 757476): 2,
 (752013, 757937): 2,
 (752013, 785916): 2,
 (752013, 761266): 2,
 (752013, 761259): 2,
 (752013, 761079): 2,
 (752013, 761160): 2,
 (752013, 754447): 2,
 (752013, 754531): 2,
 (752013, 758180): 2,
 (752013, 749659): 2,
 (752013, 758662): 2,
 (752013, 764155): 2,
 (752013, 766857): 2,
 (752013, 766832): 2,
 (752013, 765977): 2,
 (752013, 731143): 2,
 (752013, 749495): 2,
 (752013, 753918): 2,
 (752013, 761170): 2,
 (752013, 758663): 2,
 (752013, 759092): 2,
 (752013, 730929): 2,
 (752013, 765981): 2,
 (752059, 749689): 3,
 (752059, 756416): 4,
 (752059, 756431): 2,
 (752059, 

In [ ]:
import sys 

def get_size_KB(input): 
    kB = np.power(2, 20) 
    return sys.getsizeof(input) / kB  

In [ ]:
def create_rating_matrix(dataset): 
    all_options = dataset.option.unique()
    half = int(np.floor(all_options.shape[0] / 2)) 
    left_options = all_options[:half] 
    right_options = all_options[half:]
    p = itertools.product(left_options, right_options)
    print(len(p))
    option_rating = dict() 
    bills = dataset.bill.unique() 

    k = 0 
    # traverse for one pair in all bills 
    for pair in p: 
        pair_s = set(pair) 
        print(f"Size of the result {get_size_KB(option_rating)}")
        if k == 1: 
            break
        for bill in bills: 
            options = set(dataset[dataset.bill == bill]['option'])
            if(bool(pair_s & options)):
                option_rating[tuple(pair)] = option_rating.get(tuple(pair), 0) + 1  
        
        k = k + 1 
        # bıdı bıdı 
    return option_rating 

In [ ]:
len(data.option.unique())

37253

In [ ]:
(37253 * 8) / np.power(2, 20)

0.28421783447265625

In [ ]:
data_ordered = data.sort_values(by="option", ignore_index=True)

In [ ]:
# data_ordered.to_csv("../datasets/ordered_by_options.csv")

In [ ]:
data_ordered.head(5)

index  option  bill
0  1255595    2284    78
1  1255435    2284    38
2  1255576    2692    72
3   341832    3291  1139
4   128027    3558   190

# Binary Search Algorithm  


In [ ]:
from bisect import bisect_left
 
def BinarySearch(a, x):
    i = bisect_left(a, x)
    if i != len(a) and a[i] == x:
        return i
    else:
        return -1

In [ ]:
BinarySearch(data_ordered.option.to_numpy(), 2284)

0

Find the bills for single one option 

In [ ]:
ds = data_ordered.option.to_numpy() 
bs = data_ordered.bill.to_numpy() 
ds[:20], bs[:20 ]

(array([ 2284,  2284,  2692,  3291,  3558,  3701,  3864,  7507, 10494,
        11095, 12105, 14310, 16387, 16716, 16716, 17558, 18125, 18406,
        19216, 20198], dtype=int64),
 array([  78,   38,   72, 1139,  190, 1139,  158,  433, 1472,   60,   92,
        1126,  428, 1472, 1662,  159,  102, 1139, 1954, 1964], dtype=int64))

In [ ]:
ex_option = 2284 
idx_start = BinarySearch(ds, ex_option) 

bills = [bs[i] for i in range(idx_start, len(bs)) if ex_option == ds[i]]

bills

[78, 38]

In [ ]:
s1 = set(np.concatenate((bills, [43,56,78,98,3456,675,34,767])))
s2 = set([43,56,99,7,8,89,34,45])

len(s1.intersection(s2))

3

# Rating Matrix with Binary Search 

In [ ]:
def get_bills(options:np.array, option_pair:tuple, bills:np.array):
    idx_start = BinarySearch(options, option_pair[0]) 
    s1 = set([bills[i] for i in range(idx_start, len(bills)) if option_pair[0] == options[i]]) 
    idx_start = BinarySearch(options, option_pair[1]) 
    s2 = set([bills[i] for i in range(idx_start, len(bills)) if option_pair[1] == options[i]]) 
    return s1, s2

In [ ]:
def create_rating_matrix_BS(dataset_ordered, dataset_raw):
    all_options = dataset_raw.option.unique()
    half = int(np.floor(all_options.shape[0] / 2)) 
    left_options = all_options[:half] 
    right_options = all_options[half:]

    p = itertools.product(left_options, right_options)
    options = dataset_ordered.option.to_numpy() 
    bills = dataset_ordered.bill.to_numpy()
    result = dict()  
    
    i = 0 
    for pair in p: 
        s1, s2 = get_bills(options, pair, bills)
        result[tuple(pair)] = result.get(tuple(pair), 0) + 1 
        i = i + 1

        if(i % 100 == 0):
            get_size_KB(result) 

    return result 


In [ ]:
# create_rating_matrix_BS(data_ordered, data)

KeyboardInterrupt: 