# Get the Data 

In [1]:
import pandas as pd 
data = pd.read_csv("../datasets/raw_data.csv")
data.head()  

Unnamed: 0  optionId  bill
0           0    752013     1
1           1    752059     1
2           2    752123     1
3           3    785858     2
4           4    757723     2

In [8]:
data.columns = ['index', 'option', 'bill']

In [9]:
data.head() 

index  option  bill
0      0  752013     1
1      1  752059     1
2      2  752123     1
3      3  785858     2
4      4  757723     2

In [104]:
sample_set = data[:100]

In [105]:
sample_set.shape

(100, 3)

In [106]:
sample_set.bill.unique() 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
      dtype=int64)

In [107]:
# create two list of options 
all_options = sample_set.option.unique()
all_options.shape

(84,)

In [108]:
import numpy as np 

half = int(np.floor(all_options.shape[0] / 2)) 
half 

42

In [109]:
left_options = all_options[:half] 
right_options = all_options[half:]

left_options.shape[0] + right_options.shape[0]

84

In [110]:
right_options[:10], right_options[:10]

(array([749689, 756416, 756431, 756419, 754172, 761234, 757816, 747027,
        758223, 757820], dtype=int64),
 array([749689, 756416, 756431, 756419, 754172, 761234, 757816, 747027,
        758223, 757820], dtype=int64))

In [111]:
import itertools
p = itertools.product(left_options, right_options)

In [112]:
option_pairs = np.array([v for v in p])

In [113]:
option_pairs[:3]

array([[752013, 749689],
       [752013, 756416],
       [752013, 756431]], dtype=int64)

In [114]:
option_rating = dict() 
bills = sample_set.bill.unique() 

bills[:3]

array([1, 2, 3], dtype=int64)

In [115]:
for bill in bills: 
    a = set(sample_set[sample_set.bill == bill]['option'])
    b = set([756488, 752059])
    print(a, b, a & b, bool(a & b))
    break 

{752059, 752013, 752123} {756488, 752059} {752059} True


In [116]:
set(option_pairs[0])

{749689, 752013}

In [117]:
%%time 
# traverse for one pair in all bills 
for pair in option_pairs: 
    pair_s = set(pair) 
    for bill in bills: 
        options = set(sample_set[sample_set.bill == bill]['option'])
        if(bool(pair_s & options)):
            option_rating[tuple(pair)] = option_rating.get(tuple(pair), 0) + 1  

CPU times: total: 15 s
Wall time: 15.1 s


In [118]:
option_rating

{(752013, 749689): 3,
 (752013, 756416): 4,
 (752013, 756431): 2,
 (752013, 756419): 2,
 (752013, 754172): 2,
 (752013, 761234): 2,
 (752013, 757816): 3,
 (752013, 747027): 2,
 (752013, 758223): 2,
 (752013, 757820): 3,
 (752013, 756398): 2,
 (752013, 752093): 2,
 (752013, 752049): 2,
 (752013, 756906): 2,
 (752013, 711127): 2,
 (752013, 756423): 2,
 (752013, 757762): 2,
 (752013, 785918): 2,
 (752013, 757476): 2,
 (752013, 757937): 2,
 (752013, 785916): 2,
 (752013, 761266): 2,
 (752013, 761259): 2,
 (752013, 761079): 2,
 (752013, 761160): 2,
 (752013, 754447): 2,
 (752013, 754531): 2,
 (752013, 758180): 2,
 (752013, 749659): 2,
 (752013, 758662): 2,
 (752013, 764155): 2,
 (752013, 766857): 2,
 (752013, 766832): 2,
 (752013, 765977): 2,
 (752013, 731143): 2,
 (752013, 749495): 2,
 (752013, 753918): 2,
 (752013, 761170): 2,
 (752013, 758663): 2,
 (752013, 759092): 2,
 (752013, 730929): 2,
 (752013, 765981): 2,
 (752059, 749689): 3,
 (752059, 756416): 4,
 (752059, 756431): 2,
 (752059, 