# Get the Data 

In [1]:
import pandas as pd 
data = pd.read_csv("../datasets/raw_data.csv")
data.head()  

Unnamed: 0  optionId  bill
0           0    752013     1
1           1    752059     1
2           2    752123     1
3           3    785858     2
4           4    757723     2

In [8]:
data.columns = ['index', 'option', 'bill']

In [9]:
data.head() 

index  option  bill
0      0  752013     1
1      1  752059     1
2      2  752123     1
3      3  785858     2
4      4  757723     2

In [10]:
sample_set = data[:1000]

In [11]:
sample_set.shape

(1000, 3)

In [17]:
sample_set.bill.unique() 

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [22]:
# create two list of options 
all_options = sample_set.option.unique()
all_options.shape

(437,)

In [35]:
import numpy as np 

half = int(np.floor(all_options.shape[0] / 2)) 
half 

218

In [36]:
left_options = all_options[:half] 
right_options = all_options[half:]

left_options.shape[0] + right_options.shape[0]

437

In [38]:
right_options[:10], right_options[:10]

(array([756424, 749697, 715321, 758768, 785863, 802937, 802920, 802956,
        802949, 766760], dtype=int64),
 array([756424, 749697, 715321, 758768, 785863, 802937, 802920, 802956,
        802949, 766760], dtype=int64))